name: Test

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bats
        run: sudo apt-get install -y bats

      - name: Test
        run: |
          cd test
          bats *